apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # Run 2 backend pods for redundancy
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 621523791408.dkr.ecr.us-east-1.amazonaws.com/my-app:backend-latest  # Replace with your actual backend image
          env:
            - name: DB_HOST
              value: "mysql"  # Must match MySQL service name
            - name: DB_USER
              value: "appuser"
            - name: DB_PASSWORD
              value: "apppass"
            - name: DB_NAME
              value: "mydatabase"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # 🔹 Expose externally (or use LoadBalancer for AWS)

