apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 621523791408.dkr.ecr.us-east-1.amazonaws.com/my-app:frontend-latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend.default.svc.cluster.local:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

